name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20]
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        sudo systemctl start mysql.service
        mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS etoken;'
        npm install
        npm test
      env:
        CI: true
